# SITE CONFIGURATION
title: LeanArch # your site title
author: vgrgic
description: > # Meta description of Homepage
  Real world Agile, Scrum, Lean and IT architecture
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vgrgic.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Viktor Grgic
  links:
    - https://twitter.com/vgrgic
    - https://www.linkedin.com/in/vgrgic
    - https://github.com/vgrgic
    - https://keybase.io/vgrgic

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Real world Agile, Scrum, Lean and IT architecture

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: viktor@odd-e.com # email for form submission

twitter_username: vgrgic # replace with your_twitter_username or comment to remove link from footer
github_username:  vgrgic # replace with your_github_username or comment to remove link from footer
instagram_username: vgrgic # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: vgrgic # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
